### ISSUE TITLE
Moralis <> Avax hackathon prizes

### ISSUE THREAD

**Issue by PatrickAlphaC** [teterabOb/cl-oracle-easy-integration#1]
Hello!
I'm following up from the moralis <> avax hackathon (I know it was forever ago), we sent some emails to get a clean (unused) ETH address to send prizes too. 

Can you please respond to the email sent so we can send prizes?

**Comment by gilbertsahumada** [comment]
Hi Patrick,

Yeah it's been a while lol . This is the address:
*0x4Aca576d95e45d7823e3fbC1EE33C48C95a5338E*

Have an amazing day ☺😁

Regards!

**Comment by gilbertsahumada** [comment]
> Hello! I'm following up from the moralis <> avax hackathon (I know it was forever ago), we sent some emails to get a clean (unused) ETH address to send prizes too.
> 
> Can you please respond to the email sent so we can send prizes?


Hello Patrick I hope you are very well, I was remembering this and I would like to know if there is any news. 
Thank you very much

**Comment by PatrickAlphaC** [comment]
Ahhhhh sorry on the delay here! We closed up the payments but looks like we missed this one... Let me get back to you. Please ping me again in 1 week if you don't hear from me.

**Comment by gilbertsahumada** [comment]
> Ahhhhh sorry on the delay here! We closed up the payments but looks like we missed this one... Let me get back to you. Please ping me again in 1 week if you don't hear from me.

Hi Patrick, Im here to ping you xD

**Comment by PatrickAlphaC** [comment]
Thanks for the ping. Syncing with finance on this. Sorry on the massssssive delay.

**Comment by gilbertsahumada** [comment]
> Thanks for the ping. Syncing with finance on this. Sorry on the massssssive delay.

Hi Patrick, reaching out  to check if there are any news

**Comment by PatrickAlphaC** [comment]
Thanks for the ping, so sorry on the delay. I'm working with the finance team to resolve.

**Comment by PatrickAlphaC** [comment]
Sent!

https://etherscan.io/address/0x4aca576d95e45d7823e3fbc1ee33c48c95a5338e

SO sorry on the delay!
